name: Python CI

on:
  pull_request:
    branches: [ main ]  # Cambia 'main' por el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Reemplaza con la versión de Python que estás utilizando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias de tu proyecto
        pip install flake8  # Instala flake8 para verificar el estilo de código

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"
        # Ejecuta tus pruebas unitarias aquí, ajusta el comando según la estructura de tus pruebas y archivos
        # Si usas pytest, el comando podría ser 'pytest' en lugar de 'python -m unittest'

    - name: Check code style with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
